/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smsgateway.Beranda;

import java.awt.Dimension;
import smsgateway.Pelanggaran.PelanggaranView;
import smsgateway.Point.PointView;
import smsgateway.about.AboutView2;
import smsgateway.penanggung_jawab.PenangggungJawabView;
import smsgateway.siswa.ReportView;
import smsgateway.siswa.SiswaView;
import smsgateway.user.UserView;

/**
 *
 * @author NurikaFima_Pahmawati
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUser = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuData = new javax.swing.JMenu();
        menuDataUser = new javax.swing.JMenuItem();
        menuDataSiswa = new javax.swing.JMenuItem();
        menuDataPoiny = new javax.swing.JMenuItem();
        menuDataPenanggungJawab = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuLaporan = new javax.swing.JMenu();
        menuLaporanSiswa = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Welcomp\\Documents\\NetBeansProjects\\smsgateway\\background.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        menuUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Welcomp\\Documents\\NetBeansProjects\\smsgateway\\USER3.PNG")); // NOI18N
        menuUser.setText("USER");
        menuUser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        menuLogin.setText("LOGIN");
        menuUser.add(menuLogin);

        jMenuBar1.add(menuUser);

        menuData.setIcon(new javax.swing.ImageIcon("C:\\Users\\Welcomp\\Documents\\NetBeansProjects\\smsgateway\\data.PNG")); // NOI18N
        menuData.setText("DATA");
        menuData.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        menuDataUser.setText("USER");
        menuDataUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataUserActionPerformed(evt);
            }
        });
        menuData.add(menuDataUser);

        menuDataSiswa.setText("SISWA");
        menuDataSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataSiswaActionPerformed(evt);
            }
        });
        menuData.add(menuDataSiswa);

        menuDataPoiny.setText("POINT");
        menuDataPoiny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataPoinyActionPerformed(evt);
            }
        });
        menuData.add(menuDataPoiny);

        menuDataPenanggungJawab.setText("PENANGGUNG JAWAB");
        menuDataPenanggungJawab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataPenanggungJawabActionPerformed(evt);
            }
        });
        menuData.add(menuDataPenanggungJawab);

        jMenuItem2.setText("PELANGGARAN");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuData.add(jMenuItem2);

        jMenuBar1.add(menuData);

        menuLaporan.setIcon(new javax.swing.ImageIcon("C:\\Users\\Welcomp\\Documents\\NetBeansProjects\\smsgateway\\LAPORAN.jpg")); // NOI18N
        menuLaporan.setText("LAPORAN");
        menuLaporan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        menuLaporanSiswa.setText("LAPORAN SISWA");
        menuLaporanSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLaporanSiswaActionPerformed(evt);
            }
        });
        menuLaporan.add(menuLaporanSiswa);

        jMenuBar1.add(menuLaporan);

        menuAbout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Welcomp\\Documents\\NetBeansProjects\\smsgateway\\about.jpg")); // NOI18N
        menuAbout.setText("ABOUT");
        menuAbout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jMenuItem1.setText("ABOUT ME");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuAbout.add(jMenuItem1);

        jMenuBar1.add(menuAbout);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuDataUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataUserActionPerformed
        UserView uv = new UserView();
        jPanel1.add(uv);
        Dimension gs = jPanel1.getSize();
        Dimension cs = uv.getSize();
        uv.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        uv.setVisible(true);
    }//GEN-LAST:event_menuDataUserActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void menuDataPoinyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataPoinyActionPerformed
        PointView pv = new PointView();
        jPanel1.add(pv);
        Dimension gs = jPanel1.getSize();
        Dimension cs = pv.getSize();
        pv.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        pv.setVisible(true);
    }//GEN-LAST:event_menuDataPoinyActionPerformed

    private void menuDataSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataSiswaActionPerformed
        SiswaView sv = new  SiswaView();
        jPanel1.add(sv);
        Dimension gs = jPanel1.getSize();
        Dimension cs = sv.getSize();
        sv.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        sv.setVisible(true);
    }//GEN-LAST:event_menuDataSiswaActionPerformed

    private void menuDataPenanggungJawabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataPenanggungJawabActionPerformed
        PenangggungJawabView pjv = new PenangggungJawabView();
        jPanel1.add(pjv);
        Dimension gs = jPanel1.getSize();
        Dimension cs = pjv.getSize();
        pjv.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        pjv.setVisible(true);
    }//GEN-LAST:event_menuDataPenanggungJawabActionPerformed

    private void menuLaporanSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLaporanSiswaActionPerformed
        ReportView rv = new ReportView();
        jPanel1.add(rv);
        rv.setVisible(true);
    }//GEN-LAST:event_menuLaporanSiswaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        AboutView2 av = new AboutView2();
        jPanel1.add(av);
        Dimension gs = jPanel1.getSize();
        Dimension cs = av.getSize();
        av.setLocation((gs.width-cs.width)/2,(gs.height-cs.height)/2);
        av.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        PelanggaranView pv = new PelanggaranView();
        jPanel1.add(pv);
        pv.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menuAbout;
    public javax.swing.JMenu menuData;
    public javax.swing.JMenuItem menuDataPenanggungJawab;
    public javax.swing.JMenuItem menuDataPoiny;
    public javax.swing.JMenuItem menuDataSiswa;
    private javax.swing.JMenuItem menuDataUser;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JMenuItem menuLaporanSiswa;
    public javax.swing.JMenuItem menuLogin;
    public javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
